repos:
  - repo: local
    hooks:
      - id: backend-tests
        name: Backend Tests
        entry: pytest
        language: python
        additional_dependencies:
          - pytest
          - httpx
          - fastapi
          - uvicorn
          - sqlalchemy
          - pydantic-settings
          - pydantic
          - email-validator
          - python-multipart
          - python-jose[cryptography]
          - passlib[bcrypt]
          - bcrypt==4.0.1
        types: [python]
        files: ^backend/
        pass_filenames: false
        args: ["backend/tests"]
      - id: backend-pylint
        name: Backend Pylint
        entry: pylint
        language: python
        additional_dependencies:
          - pylint
          - sqlalchemy
          - fastapi
          - pydantic
          - pydantic-settings
          - python-jose[cryptography]
          - passlib[bcrypt]
        types: [python]
        files: ^backend/app/
        args: ["--rcfile=backend/.pylintrc", "--disable=import-error"]
