
services:
  backend:
    build: ./backend
    depends_on:
      - db
    container_name: continuum-backend
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/app
    ports:
      - "8001:8000"  # Map to 8001 on host to avoid conflict with jc-backend
    volumes:
      - ./backend:/app  # maps local backend folder for live code changes
    restart: unless-stopped

  frontend:
    build: ./continuum-frontend
    container_name: continuum-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./continuum-frontend:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: http://backend:8000/api  # frontend can call backend via service name
    depends_on:
      - backend
    restart: unless-stopped # will auto-restart upon docker crashes or system reboots

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5435:5432"  # Map to 5435 on host to avoid conflict with other PostgreSQL instances